"""Manage states

In our application, a state is a collection of persistent data used across
several frames.
"""

from pyglet import gl
import ctypes
import numpy as np


def bind_scene_block(program, ubo_binding_index=1):
    """This should be called once after creating a shader.
    
    Generated by AI.
    """
    block_index = gl.glGetUniformBlockIndex(program.id, b"GlobalState")
    gl.glUniformBlockBinding(program.id, block_index, ubo_binding_index)


class SceneUBO:
    """The SceneUBO enables us to bind Python variables to shader variables.
    
    It is important that there is a UniformBlock in the shader code itself,
    e.g.:

    ```glsl
    uniform GlobalState
    {
        vec3 light_position;
        vec3 camera_position;
    } globalState;
    ```
    
    Generated by AI.
    """

    def __init__(self):
        self.buffer = gl.GLuint()
        gl.glGenBuffers(1, self.buffer)

        self.binding_index = 1  # arbitrary, but must match shaders

        gl.glBindBuffer(gl.GL_UNIFORM_BUFFER, self.buffer)

        # Allocate enough space (vec3 + padding!)
        self.size = 2 * 16  # std140: vec3 = 16 bytes
        gl.glBufferData(gl.GL_UNIFORM_BUFFER, self.size,
                        None, gl.GL_DYNAMIC_DRAW)

        gl.glBindBufferBase(gl.GL_UNIFORM_BUFFER,
                            self.binding_index, self.buffer)

    def update(self, camera_pos, light_pos):
        gl.glBindBuffer(gl.GL_UNIFORM_BUFFER, self.buffer)

        data = (ctypes.c_float * 8)(  # 2 vec4 slots (std140 padding)
            light_pos[0], light_pos[1], light_pos[2], 0.0,
            camera_pos[0], camera_pos[1], camera_pos[2], 0.0,
        )

        gl.glBufferSubData(gl.GL_UNIFORM_BUFFER, 0, ctypes.sizeof(data), data)


class GlobalState:
    """
    A helper class that exposes a user friendly API to interact with the
    SceneUBO.
    
    Generated by AI.
    """

    def __init__(self):
        self.scene_ubo = SceneUBO()

    def update(self, camera_pos: np.ndarray, light_pos: np.ndarray):
        self.scene_ubo.update(
            camera_pos,
            light_pos,
        )