import sys
import numpy as np

import pywavefront

def pywavefront_obj_loader(filepath: str, flatten: bool = True):
    """Load a Wavefront scene with PyWavefront.
    
    Blender's Wavefront export implementation tries to remove duplicated
    vertices. As a result, we need to re-introduce duplication, so each vertex
    has a corresponding position and index.
    
    Generated by AI.
    
    Arguments:
    ----------
    - filepath: The path to the OBJ file on disk.
    - flatten: If true, apply numpy.ndarray.flatten() to the returned arrays.
    
    Returns:
    --------
    A tuple of the following elements are returned:
    - position: A list of vertex positions.
    - normal: A list of vertex normals. Useful for lighting computations.
    - faces: A list of indices that make triangles.
    """
    
    scene = pywavefront.Wavefront(
        filepath,
        strict=False,
        encoding="iso-8859-1",
        parse=False,
    )
    scene.parse()

    format_map = {
        "V3F": 3,
        "N3F": 3,
        "T2F": 2,
    }

    positions = []
    normals = []
    faces = []

    vertex_offset = 0

    # --- Extract raw data ---
    for mesh in scene.meshes.values():
        for material in mesh.materials:
            verts = material.vertices
            fmt = material.vertex_format.split('_')

            stride = sum(format_map[token] for token in fmt)

            offset = 0
            pos_offset = None
            norm_offset = None

            for token in fmt:
                if token == "V3F":
                    pos_offset = offset
                    offset += 3
                elif token == "N3F":
                    norm_offset = offset
                    offset += 3
                elif token == "T2F":
                    offset += 2

            count = len(verts) // stride

            for i in range(count):
                base = i * stride

                px, py, pz = verts[base + pos_offset: base + pos_offset + 3]
                positions.append((px, py, pz))

                if norm_offset is not None:
                    nx, ny, nz = verts[base + norm_offset: base + norm_offset + 3]
                    normals.append((nx, ny, nz))
                else:
                    normals.append((0.0, 0.0, 0.0))

            for i in range(0, count, 3):
                faces.append((
                    vertex_offset + i,
                    vertex_offset + i + 1,
                    vertex_offset + i + 2,
                ))

            vertex_offset += count

    # --- Deduplicate ---
    unique = {}
    new_positions = []
    new_normals = []
    new_faces = []

    for face in faces:
        new_face = []
        for idx in face:
            key = (positions[idx], normals[idx])

            if key not in unique:
                unique[key] = len(new_positions)
                new_positions.append(positions[idx])
                new_normals.append(normals[idx])

            new_face.append(unique[key])

        new_faces.append(tuple(new_face))

    # --- Convert to numpy ---
    pos_arr = np.array(new_positions, dtype=np.float32)
    norm_arr = np.array(new_normals, dtype=np.float32)
    face_arr = np.array(new_faces, dtype=np.int32)

    if flatten:
        pos_arr = pos_arr.flatten()
        norm_arr = norm_arr.flatten()
        face_arr = face_arr.flatten()

    return pos_arr, norm_arr, face_arr

def load_obj(filepath, flatten=True):
    """
    Load vertex positions and face indices from a Wavefront OBJ file.

    Returns:
        vertices: list of [x, y, z]
        indices: list of [i0, i1, i2] (0-based)
    """
    vertex_positions = []
    vertex_normals = []
    indices = []

    with open(filepath, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue

            parts = line.split()
            prefix = parts[0]

            # Vertex positions
            if prefix == "v":
                x, y, z = map(float, parts[1:4])
                vertex_positions.append([x, y, z])
            
            # Vertex normals to compute reflections
            if prefix == "vn":
                x, y, z = map(float, parts[1:4])
                vertex_normals.append([x, y, z])

            # Faces
            elif prefix == "f":
                face_indices = []
                for v in parts[1:]:
                    # Handle v, v/vt, v//vn, v/vt/vn
                    idx = int(v.split("/")[0]) - 1
                    face_indices.append(idx)

                # Triangulate polygon faces
                for i in range(1, len(face_indices) - 1):
                    indices.append([
                        face_indices[0],
                        face_indices[i],
                        face_indices[i + 1]
                    ])

    if flatten:
        vertex_positions = [
            x
            for xs in vertex_positions
            for x in xs
        ]
        vertex_normals = [
            x
            for xs in vertex_normals
            for x in xs
        ]
        indices = [
            x
            for xs in indices
            for x in xs
        ]
    
    print(len(vertex_positions))
    print(len(vertex_normals))

    return np.array(vertex_positions), np.array(vertex_normals), np.array(indices)



if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: python {sys.argv[0]} <model.obj>")
        sys.exit(1)

    filename = sys.argv[1]
    positions, normals, indices = load_obj(filename)

    print(f"Loaded: {filename}")
    print(f"Vertex Positions: {positions}")
    print(f"Vertex Normals: {normals}")
    print(f"Indices: {indices}")
